=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/ParamInfo-1.0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="paramInfo">
        <xs:complexType>
            <xs:all>
                <xs:element name="programMetaData" >
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="hasParFile" type="xs:boolean"/>
                            <xs:element name="parFileOptionName" type="xs:string" default="par" minOccurs="0"/>
                            <xs:element name="subPanel0Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel1Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel2Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel3Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel4Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="numColumns" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="columnWidth" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="progressRegex" type="xs:string" minOccurs="0"/>
                            <xs:element name="hasProgramDependency" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "programName"  type="xs:string" />
                                        <xs:element name = "programParamInfo" type="xs:string" />
                                        <xs:element name="isDefault" type="xs:boolean" minOccurs=" 0"/>
                                    </xs:all>
                                </xs:complexType>
                                    </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="options">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="option" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="value" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="default" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="source" type="xs:string" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="programName" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                    <xs:element name="programParamInfo" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                </xs:sequence>
                                                <xs:attribute name="isProgram" type="xs:boolean">

                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="order" type="xs:string" minOccurs="0"/>
                                        <xs:element name="aliases" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alias" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="validValues" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="validValue" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="value" type="xs:string">
                                                                    <xs:alternative test="@type eq 'string'"
                                                                                    type="xs:string"/>
                                                                    <xs:alternative test="@type eq 'int'"
                                                                                    type="xs:int"/>
                                                                    <xs:alternative test="@type eq 'boolean'"
                                                                                    type="xs:boolean"/>
                                                                    <xs:alternative test="@type eq 'float'"
                                                                                    type="xs:float"/>
                                                                    <xs:alternative test="@type eq 'double'"
                                                                                    type="xs:double"/>
                                                                </xs:element>
                                                                <xs:element name="description" type="xs:string"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string" minOccurs="0"/>
                                    </xs:all>
                                    <xs:attribute name="type" default="string">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="string"/>
                                                <xs:enumeration value="int"/>
                                                <xs:enumeration value="boolean"/>
                                                <xs:enumeration value="float"/>
                                                <xs:enumeration value="double"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="runtimeOption" type="xs:boolean" default="true"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l1bextract_oci.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <default></default>
            <description>input OCI L1B datafile</description>
            <source>command line</source>
            <usedAs>argument</usedAs>
            <order>0</order>
        </option>
        <option type="int">
            <name>--spixl</name>
            <value></value>
            <default></default>
            <description>start pixel number</description>
            <usedAs>option</usedAs>
            <order>1</order>
        </option>
        <option type="int">
            <name>--epixl</name>
            <value></value>
            <default></default>
            <description>end pixel number</description>
            <usedAs>option</usedAs>
            <order>2</order>
        </option>
        <option type="int">
            <name>--sline</name>
            <value></value>
            <default></default>
            <description>start scan line</description>
            <usedAs>option</usedAs>
            <order>3</order>
        </option>
        <option type="int">
            <name>--eline</name>
            <value></value>
            <default></default>
            <description>end scan line</description>
            <usedAs>option</usedAs>
            <order>4</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default></default>
            <description>output file name</description>
            <usedAs>argument</usedAs>
            <order>7</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l3bin.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>true</hasParFile>
        <parFileOptionName>parfile</parFileOptionName>
        <!--irow:   500 of     4320 Tue Jun 26 15:35:10 2012-->
        <progressRegex>irow: +(\d+) of +(\d+)</progressRegex>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <default></default>
            <description>listfile of input binfiles</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <order>0</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default>color</default>
            <description>color bin filename</description>
            <alias>ofile1</alias>
            <order>1</order>
        </option>
        <option type="string">
            <name>prod</name>
            <value></value>
            <default></default>
            <description>data products list</description>
            <colSpan>2</colSpan>
            <order>2</order>
        </option>
        <!--<option type="string">-->
        <!--<name>reduce_fac</name>-->
        <!--<value></value>-->
        <!--<default></default>-->
        <!--<description>scale reduction factor (power of 2)</description>-->
        <!--<order>3</order>-->
        <!--</option>-->

        <!--<option type="boolean">-->
        <!--<name>noext</name>-->
        <!--<value></value>-->
        <!--<default>false</default>-->
        <!--<description>set to 1 to suppress generation of external files-->
        <!--[default=0, (1 for "regional" prodtype)]-->
        <!--</description>-->
        <!--<order>8</order>-->
        <!--</option>-->
        <option type="boolean">
            <name>verbose</name>
            <value>true</value>
            <default>false</default>
            <description>Allow more verbose screen messages [default=0]</description>
            <order>3</order>
        </option>

        <option type="int">
            <name>resolve</name>
            <value></value>
            <default></default>
            <description>bin resolution</description>
            <source>default</source>
            <validValue>
                <value></value>
                <description>bin resolution</description>
            </validValue>
            <validValue>
                <value>HH</value>
                <description>50m</description>
            </validValue>
            <validValue>
                <value>HQ</value>
                <description>100m</description>
            </validValue>
            <validValue>
                <value>Q</value>
                <description>250m</description>
            </validValue>
            <validValue>
                <value>H</value>
                <description>500m</description>
            </validValue>
            <validValue>
                <value>1</value>
                <description>1.1km</description>
            </validValue>
            <validValue>
                <value>2</value>
                <description>2.3km</description>
            </validValue>
            <validValue>
                <value>4</value>
                <description>4.6km</description>
            </validValue>
            <validValue>
                <value>9</value>
                <description>9.2km</description>
            </validValue>
            <validValue>
                <value>18</value>
                <description>18.5km</description>
            </validValue>
            <validValue>
                <value>36</value>
                <description>36km</description>
            </validValue>
            <validValue>
                <value>QD</value>
                <description>0.25 degree</description>
            </validValue>
            <validValue>
                <value>HD</value>
                <description>0.5 degree</description>
            </validValue>
            <validValue>
                <value>1D</value>
                <description>1 degree</description>
            </validValue>
            <usedAs>option</usedAs>
            <order>4</order>
        </option>


        <option type="int">
            <name>reduce_fac</name>
            <value></value>
            <default></default>
            <description>scale reduction factor (power of 2)</description>
            <order>5</order>
        </option>

        <option type="float">
            <name>latnorth</name>
            <value></value>
            <default></default>
            <description>Northernmost latitude (default=+90)</description>
            <order>6</order>
        </option>
        <option type="float">
            <name>latsouth</name>
            <value></value>
            <default></default>
            <description>Southernmost latitude (default=-90)</description>
            <order>7</order>
        </option>

        <option type="float">
            <name>lonwest</name>
            <value></value>
            <default></default>
            <description>Westernmost longitude (default=-180)</description>
            <order>8</order>
        </option>
        <option type="float">
            <name>loneast</name>
            <value></value>
            <default></default>
            <description>Easternmost longitude (default=+180)</description>
            <order>9</order>
        </option>


        <option type="string">
            <name>composite_scheme</name>
            <value></value>
            <default></default>
            <description>composite scheme (min/max)</description>
            <usedAs>option</usedAs>
            <order>10</order>
        </option>

        <option type="string">
            <name>composite_prod</name>
            <value></value>
            <default></default>
            <description>composite product field name</description>
            <usedAs>option</usedAs>
            <order>11</order>
        </option>



        <option type="string">
            <name>pversion</name>
            <value></value>
            <default></default>
            <description>production version [default=Unspecified]</description>
            <order>12</order>
        </option>

        <option type="string">
            <name>oformat</name>
            <value>netCDF4</value>
            <default></default>
            <description>color file format; default is the same format as input file(s)</description>

            <source></source>
            <validValues>
                <validValue>
                    <value></value>
                    <description>color file format; default is the same format as input file(s)</description>
                </validValue>
                <validValue>
                    <value>HDF4</value>
                    <description>HDF4</description>
                </validValue>
                <validValue>
                    <value>netCDF4</value>
                    <description>netCDF4</description>
                </validValue>
                <validValue>
                    <value>HDF5</value>
                    <description>HDF5</description>
                </validValue>
            </validValues>
            <order>13</order>
        </option>


    </options>
</paramInfo>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l2extract.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <value></value>
            <default></default>
            <description>input SEAWIFS L1A datafile</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <usedAs>option</usedAs>
            <order>0</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default></default>
            <description>output L2 file name</description>
            <usedAs>option</usedAs>
            <order>1</order>
        </option>
        <option type="int">
            <name>spix</name>
            <value></value>
            <default></default>
            <description>start pixel number (1-based)</description>
            <usedAs>option</usedAs>
            <order>2</order>
        </option>
        <option type="int">
            <name>epix</name>
            <value></value>
            <default></default>
            <description>end pixel number (1-based)</description>
            <usedAs>option</usedAs>
            <order>3</order>
        </option>
        <option type="int">
            <name>sline</name>
            <value></value>
            <default></default>
            <description>start line (1-based)</description>
            <usedAs>option</usedAs>
            <order>4</order>
        </option>
        <option type="int">
            <name>eline</name>
            <value></value>
            <default></default>
            <description>end line (1-based)</description>
            <usedAs>option</usedAs>
            <order>5</order>
        </option>
<!--        <option type="int">-->
<!--            <name>pix_sub</name>-->
<!--            <value>1</value>-->
<!--            <default></default>-->
<!--            <description>pixel subsampling rate</description>-->
<!--            <usedAs>option</usedAs>-->
<!--            <order>5</order>-->
<!--        </option>-->
<!--        <option type="int">-->
<!--            <name>sc_sub</name>-->
<!--            <value>1</value>-->
<!--            <default></default>-->
<!--            <description>scan line subsampling rate</description>-->
<!--            <usedAs>option</usedAs>-->
<!--            <order>6</order>-->
<!--        </option>-->
        <option type="string">
            <name>product</name>
            <value></value>
            <default></default>
            <description>product list (optional)</description>
            <usedAs>option</usedAs>
            <order>6</order>
        </option>
        <option type="string">
            <name>wavelist</name>
            <value></value>
            <default></default>
            <description>product list (optional)</description>
            <usedAs>option</usedAs>
            <order>7</order>
        </option>
        <option type="string">
            <name>suite</name>
            <value></value>
            <default></default>
            <description></description>
            <usedAs>option</usedAs>
            <order>8</order>
        </option>

    </options>
</paramInfo>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/update_luts.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>none</parFileOptionName>
        <progressRegex>Installing .+(\d+) of (\d+)</progressRegex>
    </programMetaData>
    <options>
<!--        <option type="boolean">-->
<!--            <name>aquarius</name>-->
<!--            <value>true</value>-->
<!--            <default>true</default>-->
<!--            <usedAs>flag</usedAs>-->
<!--            <description>install Aquarius files</description>-->
<!--            <order>2</order>-->
<!--        </option>-->
        <option type="boolean">
            <name>aqua</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install MODIS Aqua files</description>
            <order>8</order>
        </option>
        <option type="boolean">
            <name>terra</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install MODIS Terra files</description>
            <order>9</order>
        </option>
        <option type="boolean">
            <name>seawifs</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install SeaWIFS files</description>
            <order>18</order>
        </option>
        <option type="boolean">
            <name>viirsn</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install VIIRS SNPP files</description>
            <order>19</order>
        </option>
        <option type="boolean">
            <name>viirsj1</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install VIIRS JPSS1 files</description>
            <order>20</order>
        </option>
        <!--<option type="button">-->
            <!--<name>update luts</name>-->
            <!--<value></value>-->
            <!--<default></default>-->
            <!--<description>update luts for a given mission. MISSION is either seawifs, aqua, terra, or aquarius-->
            <!--</description>-->
            <!--<usedAs>button</usedAs>-->
            <!--<order>15</order>-->
        <!--</option>-->
    </options>
</paramInfo>
