=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/ParamInfo-1.0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="paramInfo">
        <xs:complexType>
            <xs:all>
                <xs:element name="programMetaData" >
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="hasParFile" type="xs:boolean"/>
                            <xs:element name="parFileOptionName" type="xs:string" default="par" minOccurs="0"/>
                            <xs:element name="subPanel0Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel1Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel2Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel3Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel4Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="numColumns" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="columnWidth" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="progressRegex" type="xs:string" minOccurs="0"/>
                            <xs:element name="hasProgramDependency" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "programName"  type="xs:string" />
                                        <xs:element name = "programParamInfo" type="xs:string" />
                                        <xs:element name="isDefault" type="xs:boolean" minOccurs=" 0"/>
                                    </xs:all>
                                </xs:complexType>
                                    </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="options">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="option" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="value" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="default" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="source" type="xs:string" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="programName" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                    <xs:element name="programParamInfo" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                </xs:sequence>
                                                <xs:attribute name="isProgram" type="xs:boolean">

                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="order" type="xs:string" minOccurs="0"/>
                                        <xs:element name="aliases" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alias" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="validValues" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="validValue" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="value" type="xs:string">
                                                                    <xs:alternative test="@type eq 'string'"
                                                                                    type="xs:string"/>
                                                                    <xs:alternative test="@type eq 'int'"
                                                                                    type="xs:int"/>
                                                                    <xs:alternative test="@type eq 'boolean'"
                                                                                    type="xs:boolean"/>
                                                                    <xs:alternative test="@type eq 'float'"
                                                                                    type="xs:float"/>
                                                                    <xs:alternative test="@type eq 'double'"
                                                                                    type="xs:double"/>
                                                                </xs:element>
                                                                <xs:element name="description" type="xs:string"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string" minOccurs="0"/>
                                    </xs:all>
                                    <xs:attribute name="type" default="string">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="string"/>
                                                <xs:enumeration value="int"/>
                                                <xs:enumeration value="boolean"/>
                                                <xs:enumeration value="float"/>
                                                <xs:enumeration value="double"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="runtimeOption" type="xs:boolean" default="true"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/modis_L1B.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">>
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>parfile</parFileOptionName>
        <hasGeoFile>true</hasGeoFile>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>geofile</primaryOption>
        </primaryOptions>
        <progressRegex>scan: (\d+) out of (\d+)</progressRegex>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <default></default>
            <description>Input L1A file</description>
            <source>command line</source>
            <usedAs>argument</usedAs>
            <order>0</order>
        </option>
        <option type="ifile">
            <name>geofile</name>
            <value></value>
            <default></default>
            <description>geo file</description>
            <source>command line</source>
            <usedAs>argument</usedAs>
            <order>1</order>
        </option>
        <option type="ofile">
            <name>--okm</name>
            <value></value>
            <default></default>
            <description>Output MODIS L1B 1KM HDF filename</description>
            <usedAs>option</usedAs>
            <order>2</order>
        </option>
        <option type="ofile">
            <name>--hkm</name>
            <value></value>
            <default></default>
            <description>Output MODIS L1B HKM HDF filename</description>
            <usedAs>option</usedAs>
            <order>3</order>
        </option>
        <option type="ofile">
            <name>--qkm</name>
            <value></value>
            <default></default>
            <description>Output MODIS L1B QKM HDF filename</description>
            <usedAs>option</usedAs>
            <order>4</order>
        </option>
        <option type="ofile">
            <name>--obc</name>
            <value></value>
            <default></default>
            <description>Output MODIS L1B OBC HDF filename</description>
            <usedAs>option</usedAs>
            <order>5</order>
        </option>
        <option type="string">
            <name>--lutver</name>
            <value></value>
            <default></default>
            <description>L1B LUT version number</description>
            <usedAs>option</usedAs>
            <order>6</order>
        </option>
        <option type="dir">
            <name>--lutdir</name>
            <value></value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>option</usedAs>
            <order>7</order>
        </option>
        <option type="boolean">
            <name>--del-okm</name>
            <value></value>
            <default></default>
            <description>Delete 1km resolution L1B file</description>
            <usedAs>flag</usedAs>
            <order>8</order>
        </option>
        <option type="boolean">
            <name>--del-hkm</name>
            <value></value>
            <default></default>
            <description>Delete 500m resolution L1B file</description>
            <usedAs>flag</usedAs>
            <order>9</order>
        </option>
        <option type="boolean">
            <name>--del-qkm</name>
            <value></value>
            <default></default>
            <description>Delete 250m resolution L1B file</description>
            <usedAs>flag</usedAs>
            <order>10</order>
        </option>
        <option type="boolean">
            <name>--keep-obc</name>
            <value></value>
            <default></default>
            <description>Save onboard calibration file</description>
            <usedAs>flag</usedAs>
            <order>11</order>
        </option>
        <option type="boolean">
            <name>--log</name>
            <value></value>
            <default></default>
            <description>Save processing log file(s)</description>
            <usedAs>flag</usedAs>
            <order>12</order>
        </option>
        <option type="boolean">
            <name>--verbose</name>
            <value>true</value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>flag</usedAs>
            <order>13</order>
        </option>
        <option type="button">
            <name>update luts</name>
            <value></value>
            <default></default>
            <description>update luts for a given mission. MISSION is either seawifs, aqua, or terra
            </description>
            <usedAs>button</usedAs>
            <order>14</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/georegion_gen.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>ifiles</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifiles</name>
            <value></value>
            <default></default>
            <description>input (either WKT or Shapefiles)</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <usedAs>option_minusminus</usedAs>
            <order>0</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value>l2merged.nc</value>
            <default></default>
            <description>region masked output file</description>
            <alias>ofile1</alias>
            <usedAs>option_minusminus</usedAs>
            <order>1</order>
        </option>

        <option type="float">
            <name>stepsize</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>stepsize along latitude (resolution in degrees)</description>
            <usedAs>option_minusminus</usedAs>
            <order>2</order>
        </option>

        <option type="boolean">
            <name>wkt</name>
            <value>false</value>
            <default>false</default>
            <description>indicate that input files are ASCII files which contains WKT strings</description>
            <usedAs>flag_minusminus</usedAs>
            <order>3</order>
        </option>

        <option type="boolean">
            <name>global_set</name>
            <value>false</value>
            <default>false</default>
            <description>indicate global coverage</description>
            <usedAs>option_minusminus</usedAs>
            <order>4</order>
        </option>
    </options>
</paramInfo>
